/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dominio.Juego;
import Dominio.Jugador;
import Dominio.Panel;
import Dominio.Partida;
import Dominio.Tablero;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JColorChooser;

/**
 *
 * @author horaciochagas
 */
public class VentanaPartidaNueva extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPartidaNueva
     */
    private Juego miJuego;

    public VentanaPartidaNueva(Juego juego) {
        miJuego = juego;
        initComponents();

        final ArrayList<Jugador> jugadores = juego.getListaJugadores();
        Color colorJugadorBlanco = (Color.white);
        Color colorJugadorNegro = (Color.black);

        this.jComboBoxJugadorBlanco.addItem("Seleccione un Jugador");
        this.rellenarComboJugadorBlanco(jugadores);

//        this.jComboBoxJugadorBlanco.addActionListener(new ActionListener() {
//            public void actionPerfomed(ActionEvent event) {
//                for (int i = 0; i < jugadores.size(); i++) {
//                    Jugador jugadorBlanco = jugadores.get(i);
//                    jComboBoxJugadorBlanco.addItem(jugadorBlanco.getAlias());
//
//                }
//            }
//        });
//        Object alias = jComboBoxJugadorBlanco.getSelectedItem().toString();
//        for (int i=0; i< jugadores.size(); i++){
//        if (jugadores.get(i).getAlias().equals(alias))
//            jugadores.remove(jugadores.get(i));
//        } 
        jComboBoxJugadorBlanco.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent arg0) {

                String jugadorBlanco = jComboBoxJugadorBlanco.getSelectedItem().toString();
                rellenarComboJugadorNegro(jugadorBlanco, jugadores);
            }
        });

        //comm
        for (int i = 0; i < jugadores.size(); i++) {
            Jugador jugadorBlanco = jugadores.get(i);
            jComboBoxJugadorNegro.addItem(jugadorBlanco.getAlias());

        }

        for (int i = 4; i <= 8; i += 2) {
            String tablero = i + " x " + i;
            jComboBoxTablero.addItem(tablero);
        }

        jComboBoxTablero.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                int seleccionTablero = jComboBoxTablero.getSelectedItem().toString().charAt(0) - 49;
                rellenarComboPanel(seleccionTablero);
            }

        }
        );

        jComboBoxPanel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                int panel = 0;
                int tablero = jComboBoxTablero.getSelectedItem().toString().charAt(0) - 48;

                try {
                    panel = jComboBoxPanel.getSelectedItem().toString().charAt(0) - 48;
                } catch (Exception e) {

                }
                try {
                    rellenarComboFichas(tablero, panel);
                } catch (Exception e) {

                }
            }

        }
        );

        //String tablero = jComboBoxTablero.getSelectedItem().toString();
        /* SELECCIONTABLERO CONVIERTE A STRING LO SELECCIONADO EN EL COMBOBOX DE TABLERO,
         LUEGO DE ESE STRING TOMA EL PRIMER CARACTER, QUE CORRESPONDE AL LARGO DE TABLERO 
         Y A ESE CARACTER LE RESTA 49 PARA OBTENER SU VALOR EN INT DE ACUERDO A LA TABLA ASCII
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPanel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTablero = new javax.swing.JComboBox();
        jComboBoxFichas = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelTablero = new javax.swing.JLabel();
        labelPanel = new javax.swing.JLabel();
        labelFichas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxJugadorBlanco = new javax.swing.JComboBox();
        jComboBoxJugadorNegro = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonColorJBlanco = new javax.swing.JButton();
        botonColorJugadorNegro = new javax.swing.JButton();
        labelJugadorBlanco = new javax.swing.JLabel();
        labelJugadorNegro = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelMensajes = new javax.swing.JLabel();

        jLabel8.setText("Nueva Partida");

        jTextField1.setText("Nueva Partida");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Panel");

        jLabel3.setText("Tablero");

        jComboBoxFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFichasActionPerformed(evt);
            }
        });

        jLabel5.setText("Fichas");

        jLabel7.setText("Seleccione el tipo de Juego");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(jComboBoxTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(labelTablero)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFichas)
                    .addComponent(labelPanel))
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTablero)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxFichas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFichas))
        );

        jComboBoxJugadorBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJugadorBlancoActionPerformed(evt);
            }
        });

        jLabel1.setText("Jugador Blanco");

        jLabel2.setText("Jugador Negro");

        jLabel6.setText("Seleccione los Jugadores");

        botonColorJBlanco.setText("Color");
        botonColorJBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorJBlancoActionPerformed(evt);
            }
        });

        botonColorJugadorNegro.setText("Color");
        botonColorJugadorNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorJugadorNegroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(jComboBoxJugadorBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelJugadorBlanco)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxJugadorNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonColorJBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonColorJugadorNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelJugadorNegro)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJugadorBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(botonColorJBlanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelJugadorBlanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJugadorNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(botonColorJugadorNegro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJugadorNegro)
                .addContainerGap())
        );

        jButtonJugar.setText("Jugar!");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nueva Partida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMensajes)
                            .addComponent(jButton2))
                        .addGap(706, 706, 706)
                        .addComponent(jButtonJugar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(labelMensajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJugar)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
        Partida partida = new Partida();
        //  unaPartida.setJugadorBlanco(jugadorBlanco);
        String aliasBlanco = "";
        String aliasNegro = "";
        Jugador jugadorBlanco = null;
        Jugador jugadorNegro = null;
        Tablero tablero;
        Panel panel;
        Color colorJugadorBlanco = (Color.RED);
        Color colorJugadorNegro = (Color.BLUE);
        int fichas = 1;
        int largoTablero = 0;
        int largoPanel = 0;

        aliasBlanco = jComboBoxJugadorBlanco.getSelectedItem().toString();
        aliasNegro = jComboBoxJugadorNegro.getSelectedItem().toString();
        this.labelTablero.setText("Por favor seleccione el tablero");
        try {

            largoTablero = jComboBoxTablero.getSelectedItem().toString().charAt(0) - 48;
        } catch (Exception e) {
            this.labelTablero.setForeground(Color.red);
            this.labelTablero.setText("Por favor seleccione el tablero");
        }

        if (largoPanel == 0) {

            try {
                largoPanel = jComboBoxPanel.getSelectedItem().toString().charAt(0) - 48;
                this.labelPanel.setText(null);
            } catch (Exception e) {
                this.labelPanel.setForeground(Color.red);
                this.labelPanel.setText("Por favor seleccione  el Panel");
            }

        }

        if (aliasBlanco.isEmpty()) {
            this.labelJugadorBlanco.setForeground(Color.red);
            this.labelJugadorBlanco.setText("Por favor seleccione el jugador blanco");
        } else {
            jugadorBlanco = miJuego.BuscarJugadorPorAlias(aliasBlanco);

        }

        if (aliasNegro.isEmpty()) {
            this.labelJugadorNegro.setForeground(Color.red);
            this.labelJugadorBlanco.setText("Por favor seleccione el jugador negro");
        } else {
            jugadorNegro = miJuego.BuscarJugadorPorAlias(aliasNegro);
        }

        try {
            fichas = (Integer) jComboBoxFichas.getSelectedItem() * 2;
            this.labelFichas.setText(null);
        } catch (Exception e) {
            this.labelFichas.setForeground(Color.red);
            this.labelFichas.setText("Por favor seleccione la cantidad de fichas");
        }
        if (jugadorBlanco.equals(jugadorNegro)) {
            this.labelJugadorNegro.setForeground(Color.RED);
            this.labelJugadorNegro.setText("Por favor seleccione un jugador diferente");
        } else {
            this.labelJugadorNegro.setText(null);

        }

        tablero = new Tablero(largoTablero);
        panel = new Panel(largoPanel);
        partida.setFichas(fichas);
        partida.setJugadorNegro(jugadorNegro);
        partida.setJugadorBlanco(jugadorBlanco);
        partida.setPanel(panel);
        partida.setTablero(tablero);
        partida.setFichasJBlanco(fichas);
        partida.setFichasJNegro(fichas);
        partida.setColorJugadorBlanco(colorJugadorBlanco);
        partida.setColorJugadorNegro(colorJugadorNegro);
        // VentanaJuego juego = new VentanaJuego(miJuego, partida);
        //juego.setVisible(true);
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jComboBoxJugadorBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJugadorBlancoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxJugadorBlancoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonColorJBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorJBlancoActionPerformed
        // TODO add your handling code here:

//AGREGAR COLORES PARA EL BOTON BALNCO ACA
        Color colorBlanco = JColorChooser.showDialog(null, "Elija un color", Color.blue);

    }//GEN-LAST:event_botonColorJBlancoActionPerformed

    private void botonColorJugadorNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorJugadorNegroActionPerformed
        // TODO add your handling code here:
       // AGREGAR COLORES PARA EL JUGADOR NEGRO ACA
        Color colorNegro = JColorChooser.showDialog(null, "Elija un color", Color.yellow);
    }//GEN-LAST:event_botonColorJugadorNegroActionPerformed

    private void jComboBoxFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFichasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFichasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidaNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidaNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidaNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidaNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaPartidaNueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonColorJBlanco;
    private javax.swing.JButton botonColorJugadorNegro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JComboBox jComboBoxFichas;
    private javax.swing.JComboBox jComboBoxJugadorBlanco;
    private javax.swing.JComboBox jComboBoxJugadorNegro;
    private javax.swing.JComboBox jComboBoxPanel;
    private javax.swing.JComboBox jComboBoxTablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelFichas;
    private javax.swing.JLabel labelJugadorBlanco;
    private javax.swing.JLabel labelJugadorNegro;
    private javax.swing.JLabel labelMensajes;
    private javax.swing.JLabel labelPanel;
    private javax.swing.JLabel labelTablero;
    // End of variables declaration//GEN-END:variables

    //CARGA EL COMBOBOX DE PANEL EN BASE A LO QUE SE SELECCIONE EN EL COMBOBOX DE TABLERO
    public void rellenarComboPanel(int tablero) {
        jComboBoxPanel.removeAllItems();
        for (int i = 2; i < tablero; i += 2) {
            String panel = i + " x " + i;
            jComboBoxPanel.addItem(panel);
        }
    }

    public void rellenarComboFichas(int tablero, int panel) {
        jComboBoxFichas.removeAllItems();
        if (panel != 0) {
            int fichasMax = ((tablero * tablero) + (panel * panel)) / 2;
            for (int i = 2; i <= fichasMax; i++) {
                jComboBoxFichas.addItem(i);
            }
        }
    }

    public void rellenarComboJugadorNegro(String jBlanco, ArrayList<Jugador> jugadores) {

        jComboBoxJugadorNegro.removeAllItems();
        for (int i = 0; i < jugadores.size(); i++) {
            Jugador jugador = jugadores.get(i);
            if (!jugador.getAlias().equals(jBlanco)) {
                jComboBoxJugadorNegro.addItem(jugador.getAlias());
            }
        }
    }

    public void rellenarComboJugadorBlanco(ArrayList<Jugador> jugadores) {
        this.jComboBoxJugadorBlanco.removeAllItems();
        for (int i = 0; i < jugadores.size(); i++) {
            String jugadorBlanco = jugadores.get(i).getAlias();
            jComboBoxJugadorBlanco.addItem(jugadorBlanco);

        }
    }
}
